from model.semi_supervised.model import *

DBG = False


def print_dbg(*obj):
    if DBG:
        print(obj)


def __element_wise_matmul(x, y) -> torch.Tensor:
    """
    Perform a multiplication in every object in tensor x with every object in tensor y
    :param x: A tensor
    :param y: A tensor
    :return: Element wise multiplication
    """
    ret_val = None
    for each_ix in x:
        for each_iy in y:
            res = each_ix.matmul(each_iy.transpose(0, 1)).unsqueeze(2)
            ret_val = res if ret_val is None else torch.cat((ret_val, res), 0)
    return ret_val


def __log_exp(x: torch.Tensor) -> torch.Tensor:
    x = torch.clamp(x, max=88)
    return torch.where(x > 10, x, torch.log(1 + torch.exp(x)))


# FEATURE EXTRACTOR LOSS FUNCTION SECTION #############################

def j1_loss(l, fx, fy) -> torch.Tensor:
    """
    Calculate the L1 loss which I'm not sure what loss is this...
    Shape_ref = (Batch_size (depends), 1, Len (depends))

    all input expect its shape to be same as 'Shape_ref'

    :param l: A real label from dataset (Batch_size, 1, Class num)
    :param fx: Semantic features of img modality (Batch_size, 1, feature_size)
    :param fy: Semantic features of EEG modality (Batch_size, 1, feature_size)
    :return: The J1 loss value
    """

    s_ij = __element_wise_matmul(l, l)  # Do matmul first then mask it
    s_ij[s_ij > 0] = 1  # others will be 0

    lo_ij = __element_wise_matmul(fx, fy)
    loss = (s_ij * lo_ij) - __log_exp(lo_ij)
    loss = torch.mean(- loss)
    return loss


def j2_loss(l_real: torch.Tensor, lx: torch.Tensor) -> torch.Tensor:
    """
    Calculate J2 loss
    :param l_real: A label from dataset
    :param lx: A label from image modality
              The range of value expect to be (0,1) in other words, cannot be 0 or 1
    :return: J2 loss value
    """
    lx = lx.transpose(1, 2)
    loss = torch.matmul(l_real, torch.log(lx)) + torch.matmul((1 - l_real), torch.log(1 - lx))

    loss = torch.mean(-loss)
    return loss


def j3_loss(l_real: torch.Tensor, ly: torch.Tensor):
    """
    Calculate J3 loss
    :param l_real: A label from dataset
    :param ly: A label from EEG modality
              The range of value expect to be (0,1) in other words, cannot be 0 or 1

    :return J3 loss value
    """
    return j2_loss(l_real, ly)


def j4_loss(fy_p, l_p, fx_u, l_u, ) -> torch.Tensor:
    """
    Calculate J4 loss
    :param l_p: paired label (might be a real label of fy_p)
    :param l_u: unpaired label (might be a real label of fx_u)
    :param fx_u: Semantic features from img modality (expected to be unpaired since we can find it on internet)
    :param fy_p: Semantic features from EEG modality (expected to be paired data)
    :return: J4 loss value
    """
    s_ij_bar = __element_wise_matmul(l_p, l_u)
    s_ij_bar[s_ij_bar > 0] = 1  # other will be 0

    lo_ij_bar = __element_wise_matmul(fy_p, fx_u)
    loss = (s_ij_bar * lo_ij_bar) - __log_exp(lo_ij_bar)
    loss = torch.mean(-loss)
    return loss


def j5_loss(l_real_u: torch.Tensor, lx_u: torch.Tensor):
    """
    Calculate J5 loss
    :param l_real_u: is unpaired image data
    :param lx_u: a label from unpaired image modal
    :return: J5 loss value
    """
    return j2_loss(l_real_u, lx_u)


# DISCRIMINATOR LOSS FUNCTION SECTION #############################

def l1_loss(d1: D1, x_p, x_p_gen: torch.Tensor) -> torch.Tensor:
    """
    This is function calculate the loss value
    :param d1: The discriminator (D1) model object.
    :param x_p: The image that expected to be from real dataset.
    :param x_p_gen: Expected to be generated by Generator with EEG semantic and label from EEG Extractor.
    :return: l1 loss if x and x_gen from paired data.
    """

    d1.train()

    d1_same = d1.forward(x_p, x_p)
    d1_not_same = d1.forward(x_p, x_p_gen)

    print_dbg(d1_same, d1_not_same)

    loss = torch.log(d1_same) + torch.log(1 - d1_not_same)
    loss = torch.mean(loss)
    return loss


def l3_loss(d1: D1, x_u, x_u_gen, train_gen=False) -> torch.Tensor:
    """
    Calculate l3 loss
    :param d1:
    :param x_u: The image that expected to be from real (unpaired) dataset.
    :param x_u_gen: Expected to be generated by Generator with IMG semantic (unpaired)
                   and label from IMG Extractor (unpaired).
    :param train_gen: Set this to be True when you want to train the generator
    :return: l3 loss
    """
    return l1_loss(d1, x_u, x_u_gen)


def l2_loss(d2: D2, x_p, x_p_gen, fy_p, ly_p) -> torch.Tensor:
    """
    This function calculate the l2 loss value
    :param d2: The discriminator (D2) model object
    :param x_p: The real image
    :param x_p_gen: The generated image
    :param fy_p: semantic features from EEG modality
    :param ly_p: label from EEG modality
    :return: l2 loss
    """
    d2.train()
    d2_same = d2.forward(x_p, fy_p, ly_p)
    d2_not_same = d2.forward(x_p_gen, fy_p, ly_p)

    print_dbg(d2_same, d2_not_same)

    loss = torch.log(d2_same) + torch.log(1 - d2_not_same)
    loss = torch.mean(loss)
    return loss


def l4_loss(d2: D2, x_u, x_u_gen, fx_u, lx_u) -> torch.Tensor:
    """
    Calculate l4 loss
    :param d2: The discriminator (D2) model object
    :param x_u: The real image (unpaired)
    :param x_u_gen: The generated image from Generator with IMG semantic (unpaired)
                   and label from IMG Extractor (unpaired).
    :param fx_u: semantic features from IMG modality
    :param lx_u: label from IMG modality
    :return: l4 loss
    """
    return l2_loss(d2, x_u, x_u_gen, fx_u, lx_u)


# GENERATOR LOSS FUNCTION SECTION #############################

def l1_g_loss(d1: D1, x_p: torch.Tensor, x_p_gen: torch.Tensor) -> torch.Tensor:
    """
    **This function will change D1 to be eval mode
    This will calculate the generator loss
    :param d1: Discriminator D1 model for calculate the loss
    :param x_p: The image that expected to be from real dataset.
    :param x_p_gen: Expected to be generated by Generator with
                    EEG semantic and label from EEG Extractor.
    :return: generator loss value
    """
    d1.eval()
    d1_res = d1.forward(x_p, x_p_gen)
    loss = torch.log(d1_res)
    loss = torch.mean(loss)
    return loss


def l3_g_loss(d1: D1, x_u: torch.Tensor, x_u_gen: torch.Tensor) -> torch.Tensor:
    """
    **This function will change D1 to be eval mode
    This will calculate the generator loss
    :param d1: Discriminator D1 model for calculate the loss
    :param x_u: The image that expected to be from real (unpaired) dataset.
    :param x_u_gen: Expected to be generated by Generator with IMG semantic (unpaired)
                   and label from IMG Extractor (unpaired).
    :return: generator loss value
    """
    return l1_g_loss(d1, x_u, x_u_gen)


def l2_g_loss(d2: D2, x_p_gen, fy_p, ly_p) -> torch.Tensor:
    """
    **This function will change D2 to be eval mode
    This function calculate the l2 loss value for generator object
    :param d2: The discriminator (D2) model object
    :param x_p_gen: The generated image
    :param fy_p: semantic features from EEG modality
    :param ly_p: label from EEG modality
    :return: l2 loss for train the generator
    """
    d2.eval()
    d2_res = d2.forward(x_p_gen, fy_p, ly_p)

    print_dbg(d2_res)

    loss = torch.log(d2_res)
    loss = torch.mean(loss)
    return loss


def l4_g_loss(d2: D2, x_u_gen, fy_u, ly_u) -> torch.Tensor:
    """
    **This function will change D2 to be eval mode
    This function calculate the l4 loss value for generator object
    :param d2: The discriminator (D2) model object
    :param x_u_gen: The generated image
    :param fy_u: semantic features from EEG modality
    :param ly_u: label from EEG modality
    :return: l2 loss for train the generator
    """
    return l2_g_loss(d2, x_u_gen, fy_u, ly_u)
